// Script para generar Excel de prueba con productos completos
const XLSX = require('xlsx');

// Crear workbook
const wb = XLSX.utils.book_new();

// Encabezados completos
const headers = [
  'NOMBRE*',
  'CÓDIGO*',
  'STOCK*',
  'PRECIO_COSTO*',
  'PRECIO_VENTA*',
  'CATEGORÍA*',
  'ESTADO',
  'FECHA_VENCIMIENTO',
  'PROVEEDOR_ID',
  'PROVEEDOR_NOMBRE',
  'MARCA',
  'MEDIDA_PESO',
  'STOCK_BAJO',
  'IMAGEN_URL',
  'TALLA',
  'COLOR',
  'GÉNERO',
  'TIPO_TELA',
  'GARANTÍA_DÍAS',
  'DETALLES_CLAVE',
  'ESPECIFICACIÓN_ELÉCTRICA',
  'AUTOR',
  'EDITORIAL',
  'ISBN_EAN',
  'FORMATO_LIBRO',
  'NÚMERO_PÁGINAS',
  'TIPO_MASCOTA',
  'TONO_AROMA',
  'TIPO_PIEL_CABELLO',
  'VOLUMEN_PESO_NETO',
  'MATERIAL',
  'ALTO_CM',
  'ANCHO_CM',
  'PROFUNDO_CM',
];

// Productos de prueba - diferentes clasificaciones
const productos = [
  // ROPA
  [
    'Polo Manga Corta Premium',
    'CARGA-ROPA-001',
    100,
    35.00,
    69.90,
    'ropa',
    'Disponible',
    '',
    '',
    '',
    'Adidas',
    'Unidad',
    15,
    'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400',
    'L',
    'Negro',
    'Hombre',
    'Algodón Pima 100%',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ],
  [
    'Vestido Floral Verano',
    'CARGA-ROPA-002',
    50,
    80.00,
    159.90,
    'ropa',
    'Disponible',
    '',
    '',
    '',
    'Zara',
    'Unidad',
    10,
    'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400',
    'M',
    'Azul Floral',
    'Mujer',
    'Seda mezclada',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ],
  
  // TECNOLOGÍA
  [
    'Audífonos Bluetooth Premium',
    'CARGA-TECH-001',
    40,
    120.00,
    249.90,
    'tecnología',
    'Disponible',
    '',
    '',
    '',
    'Sony',
    'Unidad',
    5,
    'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400',
    '',
    'Negro',
    '',
    '',
    730,
    'Cancelación de ruido activa, 30h batería, Bluetooth 5.2',
    'USB-C 5V/2A',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ],
  [
    'Laptop Gamer RGB',
    'CARGA-TECH-002',
    15,
    3500.00,
    5999.00,
    'tecnología',
    'Disponible',
    '',
    '',
    '',
    'ASUS',
    'Unidad',
    3,
    'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=400',
    '',
    'Negro con RGB',
    '',
    '',
    365,
    'Intel i7-12700H, RTX 3060 6GB, 16GB RAM, 512GB SSD',
    'AC 100-240V 19V/6.32A',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ],
  
  // LIBRERÍA
  [
    'El Principito - Tapa Dura',
    'CARGA-LIBRO-001',
    80,
    18.00,
    35.00,
    'librería',
    'Disponible',
    '',
    '',
    '',
    '',
    'Unidad',
    20,
    'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    'Antoine de Saint-Exupéry',
    'Salamandra',
    '978-8498381498',
    'Tapa Dura',
    96,
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ],
  [
    'Cuaderno Universitario A4',
    'CARGA-LIBRO-002',
    200,
    4.50,
    9.90,
    'librería',
    'Disponible',
    '',
    '',
    '',
    'Stanford',
    'Unidad',
    50,
    'https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=400',
    '',
    'Varios',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    'Espiral',
    100,
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ],
  
  // BELLEZA/ASEO
  [
    'Perfume Floral Elegance',
    'CARGA-BELLEZA-001',
    60,
    85.00,
    189.90,
    'belleza y aseo personal',
    'Disponible',
    '',
    '',
    '',
    'Lancôme',
    '100ml',
    15,
    'https://images.unsplash.com/photo-1541643600914-78b084683601?w=400',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    'Floral con notas de jazmín',
    '',
    '100ml',
    '',
    '',
    '',
    '',
  ],
  [
    'Shampoo Hidratante Pro',
    'CARGA-BELLEZA-002',
    150,
    12.00,
    25.90,
    'belleza y aseo personal',
    'Disponible',
    '',
    '',
    '',
    'Pantene',
    '400ml',
    30,
    'https://images.unsplash.com/photo-1631729371254-42c2892f0e6e?w=400',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    'Sin fragancia',
    'Cabello seco y maltratado',
    '400ml',
    '',
    '',
    '',
    '',
  ],
  
  // ABARROTES
  [
    'Arroz Extra Superior',
    'CARGA-ABARROTES-001',
    500,
    3.20,
    5.90,
    'abarrotes',
    'Disponible',
    '2025-12-31',
    '',
    '',
    'Costeño',
    '1kg',
    100,
    'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '1kg',
    '',
    '',
    '',
    '',
  ],
  
  // MASCOTAS
  [
    'Alimento Premium Perro Adulto',
    'CARGA-MASCOTA-001',
    100,
    45.00,
    89.90,
    'mascotas',
    'Disponible',
    '2025-06-30',
    '',
    '',
    'Pedigree',
    '15kg',
    20,
    'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=400',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    'Perro',
    '',
    '',
    '15kg',
    '',
    '',
    '',
    '',
  ],
  
  // HOGAR
  [
    'Mesa de Centro Moderna',
    'CARGA-HOGAR-001',
    25,
    280.00,
    599.00,
    'hogar y muebles',
    'Disponible',
    '',
    '',
    '',
    'IKEA',
    'Unidad',
    5,
    'https://images.unsplash.com/photo-1565191999001-551c187427bb?w=400',
    '',
    'Roble Natural',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    'Madera de Roble',
    45,
    120,
    60,
  ],
];

// Crear worksheet con headers y productos
const ws = XLSX.utils.aoa_to_sheet([headers, ...productos]);

// Estilizar (ancho de columnas)
ws['!cols'] = headers.map(() => ({ wch: 18 }));

XLSX.utils.book_append_sheet(wb, ws, 'Productos');

// Guardar archivo
XLSX.writeFile(wb, 'test_carga_masiva_completa.xlsx');

console.log('✅ Archivo test_carga_masiva_completa.xlsx generado exitosamente!');
console.log(`📦 Total de productos: ${productos.length}`);
console.log('🏷️  Clasificaciones incluidas:');
console.log('   - Ropa (2)');
console.log('   - Tecnología (2)');
console.log('   - Librería (2)');
console.log('   - Belleza/Aseo (2)');
console.log('   - Abarrotes (1)');
console.log('   - Mascotas (1)');
console.log('   - Hogar/Muebles (1)');
