version: "3.9"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: bodegia
      POSTGRES_USER: bodegia
      POSTGRES_PASSWORD: bodegia123 
    ports: 
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../db/init:/docker-entrypoint-initdb.d:ro

  api:
    build:
      context: ../../services/api      # <--- CORRECTO: Apunta a donde creamos el Dockerfile
    env_file:
      - ../../services/api/.env        # <--- CORRECTO: Apunta al .env de la API
    depends_on: 
      - db 
    ports: ["3000:3001"]

  web:
    build:
      context: ../../apps/web          # <--- CORRECTO: Apunta a donde creamos el Dockerfile Web
    env_file:
      - ../../apps/web/.env
    depends_on: 
      - api
    ports: ["5173:5173"]

volumes:
  pgdata: